[package]
name = "askbot"
version = "0.1.0"
authors = ["thomas485"]
edition = "2018"

[dependencies]
reqwest = { version="*", features = ["blocking","json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_any = "*"
twitch-irc = "*"
tokio = "*"
futures = "*"
log = "*"
env_logger = "*"
rocket = { version="*", optional = true }
#base64 = { version="*", optional = true }

[features]
default = []
webfrontend = ["rocket"]
