[package]
name = "askbot"
version = "0.1.0"
authors = ["thomas485"]
edition = "2018"

[dependencies]
reqwest = { version="*", features = ["blocking","json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
twitch-irc = "*"
tokio = "*"
futures = "*"
